del data/external/.gitkeep
del data/interim/.gitkeep
del data/processed/test/.gitkeep
del data/processed/train/.gitkeep
del data/processed/validation/.gitkeep
del data/raw/.gitkeep
del  docs/.gitkeep
del  ls/.gitkeep
del  notebooks/.gitkeep
del  references/.gitkeep
del  reports/figures/.gitkeep
del  reports/.gitkeep
del  src/data/.gitkeep
del  src/features/.gitkeep
del  src/ls/.gitkeep
del  src/visualisations/.gitkeep
del run.sh
del run.bat