rm data/external/.gitkeep
rm data/interim/.gitkeep
rm data/processed/test/.gitkeep
rm data/processed/train/.gitkeep
rm data/processed/validation/.gitkeep
rm data/raw/.gitkeep
rm  docs/.gitkeep
rm  ls/.gitkeep
rm  notebooks/.gitkeep
rm  references/.gitkeep
rm  reports/figures/.gitkeep
rm  reports/.gitkeep
rm  src/data/.gitkeep
rm  src/features/.gitkeep
rm  src/ls/.gitkeep
rm  src/visualisations/.gitkeep
rm run.bat
rm run.sh